name: "test"
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-default-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install default version
        uses: ./
        with:
          version: "0.5.4"
      - name: Use cache or install latest 0.5.5
        uses: ./
        with:
          version: "0.5"
      - name: Check that uv is installed
        run: |
          uv --version
